export const EVENT_REQUEST = "EVENT_REQUEST";
export const EVENT_REQUEST_SUCCESS = "EVENT_REQUEST_SUCCESS";
export const EVENT_REQUEST_FAILED = "EVENT_REQUEST_FAILED";

export const EVENT_DETAIL_REQUEST = "EVENT_DETAIL_REQUEST";
export const EVENT_DETAIL_SUCCESS = "EVENT_DETAIL_SUCCESS";
export const EVENT_DETAIL_FAIL = "EVENT_DETAIL_FAIL";

export const ALL_EVENTS_REQUEST = "ALL_EVENTS_REQUEST";
export const ALL_EVENTS_SUCCESS = "ALL_EVENTS_SUCCESS";
export const ALL_EVENTS_FAIL = "ALL_EVENTS_FAIL";

export const MY_EVENTS_REQUEST = "MY_EVENTS_REQUEST";
export const MY_EVENTS_SUCCESS = "MY_EVENTS_SUCCESS";
export const MY_EVENTS_FAIL = "MY_EVENTS_FAIL";

export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENTS_FAIL";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENTS_FAIL";
